/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Lourdes Zamora
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        mStratego = new javax.swing.JMenu();
        mPartidaNueva = new javax.swing.JMenuItem();
        mCargarPartida = new javax.swing.JMenuItem();
        mEliminarPartida = new javax.swing.JMenuItem();
        mConfiguracion = new javax.swing.JMenu();
        mMiPerfil = new javax.swing.JMenu();
        mUltimosJuegos = new javax.swing.JMenuItem();
        mCambiarPassword = new javax.swing.JMenuItem();
        mConectarFacebook = new javax.swing.JMenuItem();
        mEliminarCuenta = new javax.swing.JMenuItem();
        mTierraMedia = new javax.swing.JMenu();
        mRanking = new javax.swing.JMenuItem();
        mBatallas = new javax.swing.JMenuItem();
        mCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maxresdefault.jpg"))); // NOI18N

        mStratego.setText("Stratego Lord of the Rings");

        mPartidaNueva.setText("Partida Nueva");
        mPartidaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPartidaNuevaActionPerformed(evt);
            }
        });
        mStratego.add(mPartidaNueva);

        mCargarPartida.setText("Cargar Partida");
        mStratego.add(mCargarPartida);

        mEliminarPartida.setText("Eliminar Partida");
        mStratego.add(mEliminarPartida);

        MenuBar.add(mStratego);

        mConfiguracion.setText("Configuración");
        MenuBar.add(mConfiguracion);

        mMiPerfil.setText("Mi Perfil");

        mUltimosJuegos.setText("Log de mis ultimos juegos");
        mMiPerfil.add(mUltimosJuegos);

        mCambiarPassword.setText("Cambiar mi password");
        mMiPerfil.add(mCambiarPassword);

        mConectarFacebook.setText("Conectar a Facebook");
        mMiPerfil.add(mConectarFacebook);

        mEliminarCuenta.setText("Eliminar mi Cuenta");
        mMiPerfil.add(mEliminarCuenta);

        MenuBar.add(mMiPerfil);

        mTierraMedia.setText("Tierra Media");

        mRanking.setText("Ranking");
        mTierraMedia.add(mRanking);

        mBatallas.setText("Batallas");
        mTierraMedia.add(mBatallas);

        MenuBar.add(mTierraMedia);

        mCerrarSesion.setText("Cerrar Sesión");
        MenuBar.add(mCerrarSesion);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mPartidaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPartidaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPartidaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem mBatallas;
    private javax.swing.JMenuItem mCambiarPassword;
    private javax.swing.JMenuItem mCargarPartida;
    private javax.swing.JMenu mCerrarSesion;
    private javax.swing.JMenuItem mConectarFacebook;
    private javax.swing.JMenu mConfiguracion;
    private javax.swing.JMenuItem mEliminarCuenta;
    private javax.swing.JMenuItem mEliminarPartida;
    private javax.swing.JMenu mMiPerfil;
    private javax.swing.JMenuItem mPartidaNueva;
    private javax.swing.JMenuItem mRanking;
    private javax.swing.JMenu mStratego;
    private javax.swing.JMenu mTierraMedia;
    private javax.swing.JMenuItem mUltimosJuegos;
    // End of variables declaration//GEN-END:variables
}
